workflows:
  android-workflow:
    name: Build Android Release APK
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: 3.22.2
      java: 17
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - name: Set up and get Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
